#!/usr/bin/env python3
"""Regenerate the homepage clients strip from assets/clients/clients.json.

Rewrites the block between the CLIENTS:START and CLIENTS:END markers inside
index.html (#clients .client-track). Emits each logo twice — set A (visible,
accessible) and set B (aria-hidden duplicate) — so the marquee loops seamlessly.

Run after editing assets/clients/clients.json (add/remove/reorder a logo):
  python3 scripts/build_clients.py
"""
import json, os, html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAN = os.path.join(ROOT, "assets", "clients", "clients.json")
INDEX = os.path.join(ROOT, "index.html")

START = "<!-- CLIENTS:START"
END = "<!-- CLIENTS:END -->"
ONERR = ("this.style.display='none';"
         "this.nextElementSibling.style.display='inline-flex'")


def chip(c, hidden):
    alt = "" if hidden else html.escape(str(c.get("alt", c.get("fallback", ""))), quote=True)
    aria = ' aria-hidden="true"' if hidden else ""
    fb_cls = "client-chip-fallback" + (" ar" if c.get("ar") else "")
    fb_dir = ' dir="rtl"' if c.get("ar") else ""
    fb = html.escape(str(c.get("fallback", "")))
    return (
        f'          <span class="client-chip"{aria}>\n'
        f'            <img class="client-logo" src="assets/clients/{c["file"]}" '
        f'alt="{alt}" loading="lazy" onerror="{ONERR}">\n'
        f'            <span class="{fb_cls}"{fb_dir}>{fb}</span>\n'
        f'          </span>'
    )


def main():
    clients = json.load(open(MAN, encoding="utf-8"))
    if not clients:
        raise SystemExit("clients.json is empty")

    set_a = "\n".join(chip(c, False) for c in clients)
    set_b = "\n".join(chip(c, True) for c in clients)
    block = (
        START + " — generated by scripts/build_clients.py from "
        "assets/clients/clients.json. Do not edit by hand. -->\n"
        "          <!-- set A -->\n" + set_a + "\n"
        "          <!-- set B (duplicate for seamless loop) -->\n" + set_b + "\n"
        "          " + END
    )

    s = open(INDEX, encoding="utf-8").read()
    try:
        i = s.index(START)
        j = s.index(END) + len(END)
    except ValueError:
        raise SystemExit("markers not found in index.html — expected "
                         f"'{START} ... {END}' inside .client-track")
    s = s[:i] + block + s[j:]
    open(INDEX, "w", encoding="utf-8").write(s)
    print(f"rebuilt clients strip: {len(clients)} logo(s) x2 (set A + set B)")


if __name__ == "__main__":
    main()
